#!/usr/bin/env bash
set -ue

helpmsg() {
  command echo "Usage: $0 [--help | -h]" 0>&2
  command echo ""
}

link_to_homedir() {
  # command echo "backup old dotfiles..."
  # if [ ! -d "$HOME/.dotbackup" ];then
  #   command echo "$HOME/.dotbackup not found. Auto Make it"
  #   command mkdir "$HOME/.dotbackup"
  # fi

  local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
  local dotdir=$(dirname ${script_dir})
  if [[ "$HOME" != "$dotdir" ]];then
    for f in $dotdir/.??*; do
      [[ `basename $f` == ".git" ]] && continue
      [[ `basename $f` == ".gitignore" ]] && continue
      # if [[ -e "$HOME/`basename $f`" ]];then
      #   command mv "$HOME/`basename $f`" "$HOME/.dotbackup"
      # fi
      if [[ -L "$HOME/`basename $f`" ]];then
        command rm -f "$HOME/`basename $f`"
      fi
      command ln -snfv $f $HOME \
      | echo "Created the link" $(cat) \
      | sed -r "s@($f)@\x1b[1;34m\1\x1b[m@g" \
      | sed -r "s@($HOME/`basename $f`)@\x1b[1;36m\1\x1b[m@g" \
      | sed -r "s@'@@g"
    done
  else
    command echo -e "\e[1;31m same install src dest \e[m"
  fi
}

while [ $# -gt 0 ];do
  case ${1} in
    --debug|-d)
      set -uex
      ;;
    --help|-h)
      helpmsg
      exit 1
      ;;
    *)
      ;;
  esac
  shift
done

link_to_homedir
git config --global include.path "~/.gitconfig_shared"
command echo -e "\e[1;36m Install completed!!!! \e[m"
